platform :ios, '11.1'

target 'CameraVision' do
  use_frameworks!

  # dependencies
  pod 'NascentKit', :path => '../../' 
  pod 'Firebase/Core'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionBarcodeModel'
  pod 'Firebase/MLVisionTextModel'
end

